### ISSUE TITLE
Show simulation time in graphics window

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#12]
The simulation time (the time that runs faster if accelerated) should be shown on the graphics window. Maybe activated with a key input.

**Comment by avanc** [comment]
I think this is a misunderstanding. The time scale is not that important and is also printed to the console. I meant the time running within the planeworld universe. I'm not sure if this means that an internal counter is needed which is update on every physics calculation.

**Comment by bfeldpw** [comment]
Fixed with current commit. Global time counter implemented as well as 3 local counter that can be toggled by keys 1-3.
