### ISSUE TITLE
Import paths in XML should be realtive according to XML file

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#14]
Currently, the path for xml files is, where the program is executed. Instead, if an xml file imports another file, the import path should be relative to to the first xml file.

**Comment by bfeldpw** [comment]
I don't know if I understand you correctly, the paths for xml files is evaluated relativaly to the root xml file (that with the _universe_ tags).
Did you mean the lua file instead, since this doesn't work as described above, yet.

**Comment by bfeldpw** [comment]
Does commit b90e354 solve the problem?

**Comment by avanc** [comment]
No, my _issue_ is related to XML.
The following use case is problematic if the path of the root.xml is always the path for all other files:
If a child.xml includes again another grandchild.xml, the child.xml has always to know were the root file is located. But the child.xml might also be used by another root file which may be located somewhere else. Thus, grandchild.xml can't be found.

**Comment by avanc** [comment]
Problem still exists with commit b90e354:
The sputnik example at https://github.com/planeworld/examples should not work with the new PW version as lua config still points to sputnik/physics_interface.lua instead of physics_interface.lua and font config points to fonts/AnkaCoder-C87-r.ttf instead of ../fonts/AnkaCoder-C87-r.ttf
