### ISSUE TITLE
Simulation time not shown anymore

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#17]
In the latest version, the simulation time as well as the other timers are not shown in the window.

**Comment by bfeldpw** [comment]
Make two things sure:
1. Press '0' two show timers
2. With the latest commit, paths including that of fonts should now be correctly found with a relative path within the config.xml. Any workaround (before it didn't work as expected) will now produce an error. Are there any warnings about the font at console output?

**Comment by bfeldpw** [comment]
Just read the comment concerning relative paths, so point 2 won't be the reason. Nevertheless, I cannot reproduce the problem, timers show up when pressing '0'.

**Comment by avanc** [comment]
Sorry for the noise. Didn't recognized the new behaviour of the timers and didn't pressed the 0 key.
