### ISSUE TITLE
Wrong relative path while parsing xml

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#3]
The following example reads two files as expected:

    <object file="foo.xml" />
    <object file="folder/bar.xml"/>

However, if the lines are switched:

    <object file="folder/bar.xml"/>
    <object file="foo.xml" />

foo.xml is searched at folder/foo.xml.

    [warning]     []        XML Importer: XML file ./folder/foo.xml parsed with errors.                                                                                  
    [warning]     []        XML Importer: Error description: File was not found

**Comment by bfeldpw** [comment]
Fixed.
