### ISSUE TITLE
Add exit function to quit planeworld

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#35]
As I use pw also to _simulate the simulation_ a function like

```
pw.system.quit()
```

would be helpful, as I'm only interested in the text output.

In addition, a function to set the acceleration:

```
pw.system.set_acceleration(1024, false);
```

The second Boolean parameter can be used to change also accuracy (similar to Strg+a).

**Comment by bfeldpw** [comment]
Closed, functionality added within new com interface. First implementation in 00199b7db8bcc0302bc4ae9f472ccc2ca16e20aa
