### ISSUE TITLE
Add continous integration

### ISSUE THREAD

**Issue by bfeldpw** [planeworld/planeworld#53]
Similar to Lua modules [https://github.com/planeworld/examples/issues/16](url)

**Comment by avanc** [comment]
Some hints on running the image locally for testing:
https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image

**Comment by bfeldpw** [comment]
@avanc: [CircleCI](https://circleci.com/) is also worth a look.

**Comment by avanc** [comment]
Fixed with https://github.com/planeworld/planeworld/commit/53aa6813d4088814c5de226b1da6d09b07f7ccb9
