### ISSUE TITLE
Add command to center camera on object and zoom to fit screen

### ISSUE THREAD

**Issue by bfeldpw** [planeworld/planeworld#76]
A command such as "cam_fit_object" should move the main camera to objects center (COM) and zoom in/out to fit object to screen. Combined with attaching the camera to the object, this might get handy to cycle through objects. 
Additionally, an evaluation tool like a planet generator could be created in Lua, that creates a new planet on key-press and displays it on the screen at maximum size together with additional information.

**Comment by avanc** [comment]
👍
