### ISSUE TITLE
Provide shp_line as shape type

### ISSUE THREAD

**Issue by avanc** [planeworld/planeworld#79]
Similar to shp_polygon, a not closed shape should be available:
https://github.com/planeworld/planeworld/blob/b6319fb842b370f3c901c4718364b87cb0601b45/pw_physics/geometry/shape.h#L124

**Comment by bfeldpw** [comment]
A line shape is also a polygon (ShapeType::POLYGON), but its type is not PolygonType::FILLED, there are types:
- PolygonType::FILLED
- PolygonType::LINE_LOOP
- PolygonType::LINE_SINGLE
- PolygonType::LINE_STRIP

Maybe **shp_set_polytype** is what you are searching for?!
